version: 2
updates:
    - package-ecosystem: "cargo"
      directory: "/native-helper"
      schedule:
          interval: "daily"
          time: "04:00" # UTC
      open-pull-requests-limit: 1
      labels: [ ]
      assignees:
          - "vlad20012"
